import "@/app/globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { getDictionary } from "@/app/[lang]/dictionaries";
import { ThemeProvider } from "next-themes";
import { LanguagesType } from "@/types/types";
import WhatsAppWidget from "@/components/Whatsapp";
// import Footer from "@/components/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: LanguagesType }>;
}>) {
  const lang = (await params).lang;
  const dict = await getDictionary(lang);
  const menuDict = dict.layout.header.links;
  return (
    <html suppressHydrationWarning>
      <body className={`$antialiased`}>
        <ThemeProvider>
          <Header lang={lang} links={menuDict} />
          <main className="min-h-vh flex w-full flex-col items-center overflow-y-scroll">
            {children}
          </main>
          <Footer
            terms={dict.layout.footer.terms}
            privacy={dict.layout.footer.privacy}
            rights={dict.layout.footer.rights}
            lang={lang}
          />
          <WhatsAppWidget 
            title={"Francisco"}
            botMessage={dict.layout.whatsapp.botMessage}
            placeholder={dict.layout.whatsapp.placeholder}
            send={dict.layout.whatsapp.send}
          />
        </ThemeProvider>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
